# frozen_string_literal: true

source 'https://rubygems.org'

gem 'hanami', '~> 2.2'
gem 'hanami-assets', '~> 2.2'
gem 'hanami-controller', '~> 2.2'
gem 'hanami-router', '~> 2.2'
gem 'hanami-validations', '~> 2.2'
gem 'hanami-view', '~> 2.2'

gem 'net-smtp', '~> 0.5.0'
gem 'rubocop'

gem 'bcrypt', '~> 3.1', '>= 3.1.12'
gem 'warden', '~> 1.2', '>= 1.2.9'

gem 'pg'
gem 'rom', '~> 5.3'
gem 'rom-sql', '~> 3.6'

gem 'dry-types', '~> 1.0', '>= 1.6.1'
gem 'puma'
gem 'rake'

group :development do
  gem 'guard-puma'
  gem 'hanami-webconsole', '~> 2.2'
end

group :development, :test do
  gem 'dotenv'
end

group :cli, :development do
  gem 'hanami-reloader', '~> 2.2'
end

group :cli, :development, :test do
  gem 'hanami-rspec', '~> 2.2'
end

group :test do
  gem 'capybara'
  gem 'database_cleaner-sequel'
  gem 'rack-test'
end
